export const QUESTION_BANK = [
  "What is one thing that made you smile today?",
  "What’s something small you’re grateful for right now?",
  "What’s one win you had today?",
  "What’s a moment from today you want to remember?",
  "What’s something you’re looking forward to this week?",
  "What’s your current favorite song?",
  "What’s one habit you want to build?",
  "What’s one thing you learned recently?",
  "Who’s someone you appreciate and why?",
  "What’s your go-to comfort food?",
  "What’s something that challenged you today?",
  "What’s a place that makes you feel calm?",
  "What’s one thing you’re proud of this month?",
  "What’s a movie or show you recommend?",
  "What’s something you want to improve at?",
  "What’s a recent moment that made you laugh?",
  "What’s your favorite way to relax?",
  "What’s one thing you’d tell your past self?",
  "What’s something you want to try this year?",
  "What’s a skill you admire in others?",
  "What’s one thing you did well today?",
  "What’s your favorite time of day?",
  "What’s something that motivates you?",
  "What’s a goal you’re currently working toward?",
  "What’s something you enjoyed today that you usually overlook?",
  "What’s a quote you like or think about often?",
  "What’s your favorite way to spend a free hour?",
  "What’s something new you want to learn?",
  "What’s a memory that makes you smile?",
  "What’s one thing you’re excited about tomorrow?",
  "What’s your favorite season and why?",
  "What’s a habit you’re trying to break?",
  "What’s a recent challenge you overcame?",
  "What’s one thing you want to do more often?",
  "What’s something that inspires you?",
  "What’s your favorite meal of the day?",
  "What’s something you want to say thank you for?",
  "What’s a recent risk you took?",
  "What’s your favorite way to spend time with friends?",
  "What’s something that helps you focus?",
  "What’s one thing you want to simplify in your life?",
  "What’s a place you want to visit?",
  "What’s something you’re curious about?",
  "What’s one thing you’re avoiding but shouldn’t?",
  "What’s your favorite childhood memory?",
  "What’s something you want to get better at?",
  "What’s your favorite way to start the day?",
  "What’s one thing you appreciate about yourself?",
  "What’s something that drained your energy today?",
  "What’s something that gave you energy today?",
  "What’s a small goal for tomorrow?",
  "What’s your favorite way to unwind at night?",
  "What’s something you want to let go of?",
  "What’s a recent compliment you received?",
  "What’s something you want to celebrate?",
  "What’s one thing you want to do this weekend?",
  "What’s something that surprised you recently?",
  "What’s one thing you’re thankful for about today?",
  "What’s a habit that improves your mood?",
  "What’s something you want more time for?",
  "What’s a lesson today taught you?",
  "What’s your favorite thing about this week?",
  "What’s one thing you want to remember from today?",
];
